"""adding companies, buses, schedule, ticket tables

Revision ID: 5adc49f489db
Revises: 8e32feed7ae7
Create Date: 2025-04-09 18:58:32.672069

"""
from alembic import op
import sqlalchemy as sa

from app.utils.constants import MASTER_SCHEMA


# revision identifiers, used by Alembic.
revision = '5adc49f489db'
down_revision = '8e32feed7ae7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_context().dialect.default_schema_name != MASTER_SCHEMA:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('buses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('bus_number', sa.String(length=10), nullable=False),
        sa.Column('bus_type', sa.String(length=10), nullable=False),
        sa.Column('total_seats', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('schedules',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bus_id', sa.Integer(), nullable=False),
        sa.Column('route_id', sa.Integer(), nullable=False),
        sa.Column('departure_time', sa.DateTime(), nullable=False),
        sa.Column('arrival_time', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
        sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('tickets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('bus_id', sa.Integer(), nullable=False),
        sa.Column('seat_number', sa.Integer(), nullable=False),
        sa.Column('passenger_name', sa.String(length=50), nullable=False),
        sa.Column('passenger_contact', sa.String(length=20), nullable=False),
        sa.Column('passenger_email', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###


def downgrade() -> None:    
    if op.get_context().dialect.default_schema_name != MASTER_SCHEMA:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('tickets')
        op.drop_table('schedules')
        op.drop_table('buses')
        # ### end Alembic commands ###
