"""adding companies table

Revision ID: 5efe1739f94c
Revises: 21d303375512
Create Date: 2025-04-09 18:33:33.983424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efe1739f94c'
down_revision = '21d303375512'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_person_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('buses', sa.Column('company_id', sa.Integer(), nullable=False))
    op.drop_constraint('buses_branch_id_fkey', 'buses', type_='foreignkey')
    op.create_foreign_key(None, 'buses', 'companies', ['company_id'], ['id'])
    op.drop_column('buses', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buses', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'buses', type_='foreignkey')
    op.create_foreign_key('buses_branch_id_fkey', 'buses', 'branches', ['branch_id'], ['id'])
    op.drop_column('buses', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
