"""adding companies table

Revision ID: 8e32feed7ae7
Revises: 5ae22a6d1eed
Create Date: 2025-04-09 18:56:26.672326

"""
from alembic import op
import sqlalchemy as sa

from app.utils.constants import MASTER_SCHEMA


# revision identifiers, used by Alembic.
revision = '8e32feed7ae7'
down_revision = '5ae22a6d1eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    if op.get_context().dialect.default_schema_name != MASTER_SCHEMA:
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('companies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('contact_person_name', sa.String(length=50), nullable=False),
        sa.Column('email', sa.Text(), nullable=False),
        sa.Column('address', sa.String(length=300), nullable=False),
        sa.Column('phone_number', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_context().dialect.default_schema_name != MASTER_SCHEMA:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('companies')
        # ### end Alembic commands ###
