INVALID_SCHEMA = "INVALID_SCHEMA"
MASTER_SCHEMA = "public"
DB_NOT_UPTODATE = "DB_NOT_UPTODATE"
HEAD = "HEAD"
AUTHORIZATION = "Authorization"
USER_NOT_FOUND = "USER_NOT_FOUND"

# User related constants:
INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
USER_CREATED_SUCCESSFULLY = "USER_CREATED_SUCCESSFULLY"

# Branch related constants
BRANCH_CREATED_SUCCESSFULLY = "BRANCH_CREATED_SUCCESSFULLY"
CITY_NAME_ALREADY_EXISTS = "CITY_NAME_ALREADY_EXISTS"
DOMAIN_NAME_ALREADY_EXISTS = "DOMAIN_NAME_ALREADY_EXISTS"